import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";
import tailwindcss from "@tailwindcss/vite";

export default defineConfig({
  plugins: [
    react(),
    // ---- PWA plugin ----
    // Turns this app into an installable, offline-capable Progressive Web App.
    // It generates two things at build time: a service worker (the background
    // helper that caches our files so the app loads offline) and a web app
    // manifest (the "ID card" that lets the browser offer "Install app").
    tailwindcss(),
    VitePWA({
      // "autoUpdate": when we deploy a new version, the service worker updates
      // itself silently in the background. Simpler than prompting the user;
      // we can switch to a "refresh to update" prompt later (Phase 3).
      registerType: "autoUpdate",

      // Let the service worker run in `npm run dev` too, so we can test offline
      // without a full production build. (In dev it's a lighter SW; the real
      // one is generated by `npm run build`.)
      devOptions: { enabled: true },

      // Extra static files (beyond the JS/CSS Vite already handles) that the
      // service worker should be aware of.
      includeAssets: ["favicon.ico", "apple-touch-icon-180x180.png"],

      // ---- The web app manifest ----
      // This object becomes manifest.webmanifest. The browser reads it to know
      // the app's name, colours, and icons when installing it.
      manifest: {
        id: "/",                          // stable identity for the installed app (defaults to start_url; set explicitly as good practice)
        name: "Check-in app",
        short_name: "Check-in",           // shown under the home-screen icon
        description:
          "Send a check-in to your close friends when you're not okay.",
        theme_color: "#4f46e5",           // colours the title bar of the installed app
        background_color: "#ffffff",      // splash-screen background while it loads
        display: "standalone",            // open in its own window, no browser bar
        start_url: "/",                   // which page opens when launched
        icons: [
          { src: "pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "pwa-512x512.png", sizes: "512x512", type: "image/png" },
          {
            // "maskable" = the OS may crop it into a circle/squircle; this
            // version has padding so nothing important gets cut off.
            src: "maskable-icon-512x512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
        // ---- Screenshots ----
        // Shown in the richer install dialog. "wide" is used on desktop; the
        // one without form_factor (narrow) is used on mobile. Replace these
        // placeholders with real screen captures of the app before evaluation.
        screenshots: [
          {
            src: "screenshot-wide-1280x720.png",
            sizes: "1280x720",
            type: "image/png",
            form_factor: "wide",
            label: "Check-in app on desktop",
          },
          {
            src: "screenshot-narrow-720x1280.png",
            sizes: "720x1280",
            type: "image/png",
            label: "Check-in app on mobile",
          },
        ],
      },
    }),
  ],
  server: {
    host: true,
    port: 5173,
    // When the browser asks for /api/*, Vite forwards it to the backend
    // container. "backend" is the service name from docker-compose, which
    // Docker resolves to the backend container's address on the internal
    // network. This is why the frontend doesn't need to know an IP.
    proxy: {
      "/api": {
        target: "http://backend:3000",
        changeOrigin: true,
        ws: true,
      },
    },
  },
});
